const SUPABASE_URL = 'https://rphsmqppmqvqzfpcablw.supabase.co';
const SUPABASE_KEY = 'sb_publishable_vB7G9y3xTKk0swxKAbaIHQ_Gt1tshVw';
const db = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY);

const MAX_FILE_SIZE = 50 * 1024 * 1024;
const ALLOWED_IMAGES = ['image/jpeg','image/png','image/gif','image/webp'];
const ALLOWED_VIDEOS = ['video/mp4','video/webm','video/quicktime'];
let session = null;
let mode = 'login';
let feedMode = 'fyp';
let currentSearch = '';
let resultMode = 'all';

const $ = id => document.getElementById(id);

async function init(){
  const {data} = await db.auth.getSession();
  session = data.session;
  renderAccount(); renderComposer(); bindUI(); await loadFeed();
  if(session) await loadSearchHistory();
  db.auth.onAuthStateChange((_event,newSession)=>{ session=newSession; renderAccount(); renderComposer(); loadFeed(); loadSearchHistory(); });
}
function bindUI(){
  $('openAuth')?.addEventListener('click',()=>$('authPanel').classList.remove('hidden'));
  $('toggleAuth').addEventListener('click',()=>{mode=mode==='login'?'signup':'login';$('authTitle').textContent=mode==='login'?'Welcome back to LarpTok':'Join LarpTok';$('displayName').classList.toggle('hidden',mode==='login');$('username').classList.toggle('hidden',mode==='login');$('toggleAuth').textContent=mode==='login'?'Create an account':'I already have an account';});
  $('authForm').addEventListener('submit',handleAuth); $('postButton').addEventListener('click',createPost);
  $('mediaFile').addEventListener('change',()=>{const file=$('mediaFile').files[0];$('fileName').textContent=file?`${file.name} • ${formatBytes(file.size)}`:'No file selected';});
  document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');feedMode=btn.dataset.feed;loadFeed();}));
  $('searchForm').addEventListener('submit',e=>{e.preventDefault();runSearch($('searchInput').value);});
  $('searchInput').addEventListener('input',()=>{if(!$('searchInput').value.trim())renderSearchHistory();});
  $('closeDiscovery').addEventListener('click',closeDiscovery);
  document.querySelectorAll('.discoveryTab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.discoveryTab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');resultMode=btn.dataset.result;renderDiscovery();}));
}
function renderAccount(){const area=$('accountArea');if(session){area.innerHTML='<button class="ghost" id="logout">Log out</button>';$('logout').onclick=()=>db.auth.signOut();}else{area.innerHTML='<button class="ghost" id="openAuth">Log in</button>';$('openAuth').onclick=()=>{$('authPanel').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});};}}
function renderComposer(){$('composer').classList.toggle('hidden',!session);}
async function handleAuth(e){e.preventDefault();$('authMessage').textContent='';const email=$('email').value.trim(),password=$('password').value;if(mode==='login'){const {error}=await db.auth.signInWithPassword({email,password});$('authMessage').textContent=error?error.message:'Logged in!';}else{const username=$('username').value.trim().toLowerCase(),displayName=$('displayName').value.trim()||username;if(!/^[a-z0-9_]{3,24}$/.test(username)){$('authMessage').textContent='Username must be 3–24 characters using letters, numbers, or underscores.';return;}const {error}=await db.auth.signUp({email,password,options:{data:{username,display_name:displayName}}});$('authMessage').textContent=error?error.message:'Account created. Check your email if confirmation is enabled.';}}
async function createPost(){if(!session)return;const caption=$('caption').value.trim(),file=$('mediaFile').files[0];if(!caption&&!file){alert('Add a caption or choose a photo/video.');return;}if(file){if(file.size>MAX_FILE_SIZE){alert('That file is too large. The maximum is 50 MB.');return;}const allowed=file.type.startsWith('image/')?ALLOWED_IMAGES:ALLOWED_VIDEOS;if(!allowed.includes(file.type)){alert('Unsupported file type. Use JPG, PNG, GIF, WEBP, MP4, WEBM, or MOV.');return;}}const button=$('postButton');button.disabled=true;setUploadStatus(true,'Preparing upload…',5);try{let media_url=null,media_type='text';if(file){media_type=file.type.startsWith('image/')?'image':'video';setUploadStatus(true,`Uploading ${media_type}…`,20);const ext=(file.name.split('.').pop()||'bin').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`${session.user.id}/${crypto.randomUUID()}.${ext}`;const {data,error}=await db.storage.from('media').upload(path,file,{contentType:file.type,cacheControl:'3600',upsert:false});if(error)throw error;media_url=db.storage.from('media').getPublicUrl(data.path).data.publicUrl;setUploadStatus(true,'Upload complete. Publishing…',85);}else setUploadStatus(true,'Publishing…',60);const {error}=await db.from('posts').insert({user_id:session.user.id,caption,media_type,media_url});if(error)throw error;$('caption').value='';$('mediaFile').value='';$('fileName').textContent='No file selected';setUploadStatus(true,'Posted! 🎭',100);await loadFeed();setTimeout(()=>setUploadStatus(false),900);}catch(error){console.error(error);setUploadStatus(true,error.message||'Upload failed',0);setTimeout(()=>setUploadStatus(false),2500);}finally{button.disabled=false;}}
function setUploadStatus(show,text,percent){$('uploadStatus').classList.toggle('hidden',!show);$('uploadText').textContent=text;$('uploadProgress').style.width=`${Math.max(0,Math.min(100,percent))}%`;}
async function getPosts(limit=100){const {data,error}=await db.from('posts').select('id,user_id,caption,media_url,media_type,created_at,profiles(username,display_name,avatar_url),likes(user_id,created_at),comments(id,user_id,body,created_at,profiles(username))').order('created_at',{ascending:false}).limit(limit);if(error)throw error;return data||[];}
function freshness(createdAt){const ageHours=Math.max(0,(Date.now()-new Date(createdAt).getTime())/3600000);return Math.max(0,48-ageHours)/4;}
function engagementScore(post){return (post.likes?.length||0)*3+(post.comments?.length||0)*5+freshness(post.created_at)+(session&&post.user_id===session.user.id?1:0);}
async function loadFeed(){const feed=$('feed');feed.innerHTML='<div class="loading">Loading…</div>';try{let posts=await getPosts(100);if(feedMode==='following'&&session){const {data:follows}=await db.from('follows').select('following_id').eq('follower_id',session.user.id);const ids=new Set((follows||[]).map(x=>x.following_id));posts=posts.filter(p=>ids.has(p.user_id));}if(feedMode==='fyp')posts.sort((a,b)=>engagementScore(b)-engagementScore(a));if(feedMode==='trending')posts.sort((a,b)=>((b.likes?.length||0)*3+(b.comments?.length||0)*5+freshness(b.created_at)*2)-((a.likes?.length||0)*3+(a.comments?.length||0)*5+freshness(a.created_at)*2));if(!posts.length){feed.innerHTML='<div class="loading">No posts yet. Be the first LARPer to post! 🎭</div>';return;}feed.innerHTML=posts.slice(0,30).map(renderPost).join('');bindFeedActions();}catch(error){feed.innerHTML=`<div class="loading">Could not load posts: ${escapeHtml(error.message)}</div>`;}}
function bindFeedActions(){const root=$('feed');root.querySelectorAll('[data-like]').forEach(b=>b.onclick=()=>toggleLike(Number(b.dataset.like)));root.querySelectorAll('[data-follow]').forEach(b=>b.onclick=()=>toggleFollow(b.dataset.follow));root.querySelectorAll('[data-comment-form]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();await addComment(Number(f.dataset.commentForm),f.querySelector('input').value);});root.querySelectorAll('[data-hashtag]').forEach(a=>a.onclick=e=>{e.preventDefault();openHashtag(a.dataset.hashtag);});}
function renderPost(p){const profile=p.profiles||{},likes=p.likes||[],liked=session&&likes.some(x=>x.user_id===session.user.id),avatar=(profile.display_name||profile.username||'?').slice(0,1).toUpperCase();let media='';if(p.media_type==='image'&&p.media_url)media=`<img class="postMedia" src="${escapeAttr(p.media_url)}" alt="LarpTok post image" loading="lazy">`;if(p.media_type==='video'&&p.media_url)media=`<video class="postMedia" src="${escapeAttr(p.media_url)}" controls playsinline preload="metadata"></video>`;const captionHtml=renderCaption(p.caption||'');const comments=(p.comments||[]).slice(-3).map(c=>`<div class="comment"><b>@${escapeHtml(c.profiles?.username||'user')}</b> ${escapeHtml(c.body)}</div>`).join('');return `<article class="post" id="post-${p.id}"><div class="postHead"><div class="avatar">${escapeHtml(avatar)}</div><div><div class="name">${escapeHtml(profile.display_name||profile.username||'LARPer')}</div><div class="handle">@${escapeHtml(profile.username||'user')} · ${timeAgo(p.created_at)}</div></div>${session&&session.user.id!==p.user_id?`<button class="ghost followBtn" data-follow="${p.user_id}">Follow</button>`:''}</div>${media}<div class="postBody"><div>${captionHtml}</div></div><div class="actions"><button class="action ${liked?'liked':''}" data-like="${p.id}">♥ ${likes.length}</button><button class="action">💬 ${(p.comments||[]).length}</button><button class="action" onclick="sharePost('${escapeAttr(p.id)}')">↗ Share</button></div>${comments}<form class="commentBox" data-comment-form="${p.id}"><input placeholder="Add a comment…" maxlength="1000" ${session?'':'disabled'}><button class="primary" ${session?'':'disabled'}>Post</button></form></article>`;}
function renderCaption(text){return text.split(/(#[a-zA-Z0-9_]{1,50})/g).map(t=>/^#[a-zA-Z0-9_]{1,50}$/.test(t)?`<a href="#" class="hashtag" data-hashtag="${escapeAttr(t.slice(1).toLowerCase())}">${escapeHtml(t)}</a>`:escapeHtml(t)).join('');}
async function toggleLike(postId){if(!session){$('authPanel').classList.remove('hidden');return;}const {data}=await db.from('likes').select('post_id').eq('post_id',postId).eq('user_id',session.user.id).maybeSingle();if(data)await db.from('likes').delete().eq('post_id',postId).eq('user_id',session.user.id);else await db.from('likes').insert({post_id:postId,user_id:session.user.id});loadFeed();}
async function toggleFollow(userId){if(!session)return;const {data}=await db.from('follows').select('follower_id').eq('follower_id',session.user.id).eq('following_id',userId).maybeSingle();if(data)await db.from('follows').delete().eq('follower_id',session.user.id).eq('following_id',userId);else await db.from('follows').insert({follower_id:session.user.id,following_id:userId});loadFeed();}
async function addComment(postId,body){if(!session||!body.trim())return;const {error}=await db.from('comments').insert({post_id:postId,user_id:session.user.id,body:body.trim()});if(error)alert(error.message);else loadFeed();}
async function sharePost(postId){const url=`${location.origin}${location.pathname}#post-${postId}`;try{await navigator.clipboard.writeText(url);alert('Post link copied!');}catch{prompt('Copy this link:',url);}}

async function runSearch(raw){const query=raw.trim();if(!query)return;currentSearch=query;$('searchInput').value=query;if(session){await db.from('search_history').insert({user_id:session.user.id,query:query.slice(0,100)});await trimSearchHistory();}$('discovery').classList.remove('hidden');$('feed').classList.add('hidden');resultMode=query.startsWith('#')?'hashtags':'all';document.querySelectorAll('.discoveryTab').forEach(x=>x.classList.toggle('active',x.dataset.result===resultMode));await renderDiscovery();window.scrollTo({top:$('discovery').offsetTop-70,behavior:'smooth'});}
async function renderDiscovery(){const title=$('discoveryTitle'),results=$('discoveryResults');results.innerHTML='<div class="loading">Searching…</div>';try{if(resultMode==='trending'||currentSearch.toLowerCase()==='trending'){title.textContent='Trending on LarpTok';await renderTrending(results);return;}const q=currentSearch.replace(/^#/,'').replace(/^@/,'').trim();title.textContent=currentSearch.startsWith('#')?`#${q}`:currentSearch.startsWith('@')?`@${q}`:`Results for “${currentSearch}”`;const [users,posts,hashtags]=await Promise.all([searchUsers(q),searchPosts(currentSearch),searchHashtags(q)]);const sections=[];if(resultMode==='all'||resultMode==='users')sections.push(renderUserResults(users));if(resultMode==='all'||resultMode==='posts')sections.push(renderSearchPostResults(posts));if(resultMode==='all'||resultMode==='hashtags')sections.push(renderHashtagResults(hashtags));results.innerHTML=sections.filter(Boolean).join('')||'<div class="emptyState">No results found. Try another search.</div>';bindDiscoveryActions();}catch(error){results.innerHTML=`<div class="emptyState">Search failed: ${escapeHtml(error.message)}</div>`;}}
async function searchUsers(q){const safe=escapeLike(q);const {data,error}=await db.from('profiles').select('id,username,display_name,bio,avatar_url').or(`username.ilike.%${safe}%,display_name.ilike.%${safe}%`).order('username').limit(20);if(error)throw error;return data||[];}
async function searchPosts(q){const safe=escapeLike(q.replace(/^#/,'').replace(/^@/,''));const needle=`%${safe}%`;const {data,error}=await db.from('posts').select('id,user_id,caption,media_url,media_type,created_at,profiles(username,display_name,avatar_url),likes(user_id),comments(id,user_id,body,created_at,profiles(username))').ilike('caption',needle).order('created_at',{ascending:false}).limit(30);if(error)throw error;return data||[];}
async function searchHashtags(q){const {data,error}=await db.from('hashtags').select('id,name,created_at,post_hashtags(post_id)').ilike('name',`${escapeLike(q)}%`).order('name').limit(30);if(error)throw error;return data||[];}
function escapeLike(s){return String(s).replace(/[%_\\]/g,m=>`\\${m}`).replace(/,/g,'');}
function renderUserResults(users){if(!users.length)return '';return `<section class="resultSection"><div class="resultTitle">👤 Users</div>${users.map(u=>`<button class="userResult" onclick="searchUserPosts('${escapeAttr(u.username)}')"><div class="avatar">${escapeHtml((u.display_name||u.username).slice(0,1).toUpperCase())}</div><div><b>${escapeHtml(u.display_name||u.username)}</b><span>@${escapeHtml(u.username)}</span><small>${escapeHtml(u.bio||'')}</small></div></button>`).join('')}</section>`;}
function renderSearchPostResults(posts){if(!posts.length)return '';return `<section class="resultSection"><div class="resultTitle">🎬 Posts</div><div class="searchPosts">${posts.slice(0,12).map(renderPost).join('')}</div></section>`;}
function renderHashtagResults(tags){if(!tags.length)return '';return `<section class="resultSection"><div class="resultTitle">#️⃣ Hashtags</div>${tags.map(t=>`<button class="hashtagResult" onclick="openHashtag('${escapeAttr(t.name)}')"><b>#${escapeHtml(t.name)}</b><span>${t.post_hashtags?.length||0} posts</span></button>`).join('')}</section>`;}
async function openHashtag(name){currentSearch='#'+name;$('searchInput').value=currentSearch;resultMode='posts';document.querySelectorAll('.discoveryTab').forEach(x=>x.classList.toggle('active',x.dataset.result==='posts'));const results=$('discoveryResults');results.innerHTML='<div class="loading">Loading hashtag…</div>';try{const tag=await db.from('hashtags').select('id').eq('name',name).single();if(tag.error)throw tag.error;const {data,error}=await db.from('post_hashtags').select('post_id,posts(id,user_id,caption,media_url,media_type,created_at,profiles(username,display_name,avatar_url),likes(user_id),comments(id,user_id,body,created_at,profiles(username)))').eq('hashtag_id',tag.data.id);if(error)throw error;const posts=(data||[]).map(x=>x.posts).filter(Boolean).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));$('discoveryTitle').textContent='#'+name;results.innerHTML=posts.length?posts.map(renderPost).join(''):'<div class="emptyState">No posts with this hashtag yet.</div>';bindDiscoveryActions();}catch(e){results.innerHTML=`<div class="emptyState">Could not load hashtag: ${escapeHtml(e.message)}</div>`;}}
async function searchUserPosts(username){const {data,error}=await db.from('profiles').select('id,username,display_name,bio').eq('username',username).single();if(error)return;currentSearch='@'+username;$('searchInput').value=currentSearch;const posts=await db.from('posts').select('id,user_id,caption,media_url,media_type,created_at,profiles(username,display_name,avatar_url),likes(user_id),comments(id,user_id,body,created_at,profiles(username))').eq('user_id',data.id).order('created_at',{ascending:false}).limit(30);$('discoveryTitle').textContent='@'+username;$('discoveryResults').innerHTML=(posts.data||[]).map(renderPost).join('')||'<div class="emptyState">This creator has no posts yet.</div>';bindDiscoveryActions();}
async function renderTrending(results){const posts=await getPosts(100);const ranked=posts.map(p=>({...p,trendScore:(p.likes?.length||0)*3+(p.comments?.length||0)*5+freshness(p.created_at)*2})).sort((a,b)=>b.trendScore-a.trendScore).slice(0,10);const tagMap=new Map(),creatorMap=new Map();posts.forEach(p=>{for(const m of (p.caption||'').matchAll(/#([a-zA-Z0-9_]{1,50})/g)){const n=m[1].toLowerCase();tagMap.set(n,(tagMap.get(n)||0)+1);}const creator=p.profiles?.username;if(creator){const c=creatorMap.get(creator)||{username:creator,displayName:p.profiles.display_name||creator,score:0};c.score+=(p.likes?.length||0)*3+(p.comments?.length||0)*5+freshness(p.created_at);creatorMap.set(creator,c);}});const tags=[...tagMap.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10),creators=[...creatorMap.values()].sort((a,b)=>b.score-a.score).slice(0,10);results.innerHTML=`<section class="resultSection"><div class="resultTitle">🔥 Trending posts</div>${ranked.length?ranked.map(renderPost).join(''):'<div class="emptyState">No posts yet.</div>'}</section><section class="resultSection"><div class="resultTitle">#️⃣ Trending hashtags</div>${tags.length?tags.map(([name,count])=>`<button class="hashtagResult" onclick="openHashtag('${escapeAttr(name)}')"><b>#${escapeHtml(name)}</b><span>${count} recent posts</span></button>`).join(''):'<div class="emptyState">Add hashtags to help trends grow.</div>'}</section><section class="resultSection"><div class="resultTitle">👑 Trending creators</div>${creators.length?creators.map(c=>`<button class="userResult" onclick="searchUserPosts('${escapeAttr(c.username)}')"><div class="avatar">${escapeHtml(c.displayName.slice(0,1).toUpperCase())}</div><div><b>${escapeHtml(c.displayName)}</b><span>@${escapeHtml(c.username)}</span><small>Trending creator</small></div></button>`).join(''):'<div class="emptyState">No creators are trending yet.</div>'}</section>`;bindDiscoveryActions();}
function bindDiscoveryActions(){const root=$('discoveryResults');root.querySelectorAll('[data-like]').forEach(b=>b.onclick=()=>toggleLike(Number(b.dataset.like)));root.querySelectorAll('[data-follow]').forEach(b=>b.onclick=()=>toggleFollow(b.dataset.follow));root.querySelectorAll('[data-comment-form]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();await addComment(Number(f.dataset.commentForm),f.querySelector('input').value);});root.querySelectorAll('[data-hashtag]').forEach(a=>a.onclick=e=>{e.preventDefault();openHashtag(a.dataset.hashtag);});}
function closeDiscovery(){$('discovery').classList.add('hidden');$('feed').classList.remove('hidden');currentSearch='';$('searchInput').value='';}
async function loadSearchHistory(){if(!session){$('searchHistory').innerHTML='';return;}const {data}=await db.from('search_history').select('id,query,created_at').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(8);renderSearchHistory(data||[]);}
function renderSearchHistory(items){const box=$('searchHistory');if(!session){box.innerHTML='';return;}const list=items||[];box.innerHTML=list.length?`<div class="historyHeader"><span>Recent searches</span><button class="linkButton" id="clearHistory">Clear</button></div><div class="historyItems">${list.map(x=>`<button class="historyItem" data-history="${escapeAttr(x.query)}">↻ ${escapeHtml(x.query)}</button>`).join('')}</div>`:'';box.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>runSearch(b.dataset.history));box.querySelector('#clearHistory')?.addEventListener('click',clearSearchHistory);}
async function clearSearchHistory(){if(!session)return;await db.from('search_history').delete().eq('user_id',session.user.id);renderSearchHistory([]);}
async function trimSearchHistory(){if(!session)return;const {data}=await db.from('search_history').select('id').eq('user_id',session.user.id).order('created_at',{ascending:false}).range(10,100);if(data?.length)await db.from('search_history').delete().in('id',data.map(x=>x.id));}
function timeAgo(date){const seconds=Math.floor((Date.now()-new Date(date).getTime())/1000);if(seconds<60)return 'now';if(seconds<3600)return `${Math.floor(seconds/60)}m`;if(seconds<86400)return `${Math.floor(seconds/3600)}h`;return `${Math.floor(seconds/86400)}d`;}
function formatBytes(bytes){if(bytes<1024*1024)return `${(bytes/1024).toFixed(0)} KB`;return `${(bytes/1024/1024).toFixed(1)} MB`;}
function escapeHtml(s){return String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
function escapeAttr(s){return escapeHtml(s).replace(/`/g,'&#96;');}
init();