const SUPABASE_URL='https://rphsmqppmqvqzfpcablw.supabase.co';
const SUPABASE_KEY='sb_publishable_vB7G9y3xTKk0swxKAbaIHQ_Gt1tshVw';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const MAX_FILE_SIZE=50*1024*1024;
const ALLOWED=['image/jpeg','image/png','image/gif','image/webp','video/mp4','video/webm','video/quicktime'];
let session=null,mode='login',feedMode='fyp',currentSearch='',resultMode='all',activePostId=null;
const $=id=>document.getElementById(id);

async function init(){const {data}=await db.auth.getSession();session=data.session;renderAccount();renderComposer();bindUI();await loadFeed();if(session)await loadSearchHistory();db.auth.onAuthStateChange((_e,s)=>{session=s;renderAccount();renderComposer();loadFeed();loadSearchHistory();});}
function bindUI(){
 $('openAuth')?.addEventListener('click',()=>$('authPanel').classList.remove('hidden'));
 $('toggleAuth').addEventListener('click',()=>{mode=mode==='login'?'signup':'login';$('authTitle').textContent=mode==='login'?'Welcome back to LarpTok':'Join LarpTok';$('displayName').classList.toggle('hidden',mode==='login');$('username').classList.toggle('hidden',mode==='login');$('toggleAuth').textContent=mode==='login'?'Create an account':'I already have an account';});
 $('authForm').addEventListener('submit',handleAuth);$('postButton').addEventListener('click',createPost);$('mediaFile').addEventListener('change',()=>{const f=$('mediaFile').files[0];$('fileName').textContent=f?`${f.name} • ${formatBytes(f.size)}`:'No file selected';});
 document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');feedMode=b.dataset.feed;loadFeed();}));
 $('searchForm').addEventListener('submit',e=>{e.preventDefault();runSearch($('searchInput').value);});$('searchInput').addEventListener('input',()=>{if(!$('searchInput').value.trim())renderSearchHistory();});$('closeDiscovery').addEventListener('click',closeDiscovery);
 document.querySelectorAll('.discoveryTab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.discoveryTab').forEach(x=>x.classList.remove('active'));b.classList.add('active');resultMode=b.dataset.result;renderDiscovery();}));
}
function renderAccount(){const a=$('accountArea');if(session){a.innerHTML='<button class="ghost" id="logout">Log out</button>';$('logout').onclick=()=>db.auth.signOut();}else{a.innerHTML='<button class="ghost" id="openAuth">Log in</button>';$('openAuth').onclick=()=>{$('authPanel').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});};}}
function renderComposer(){$('composer').classList.toggle('hidden',!session);}
async function handleAuth(e){e.preventDefault();$('authMessage').textContent='';const email=$('email').value.trim(),password=$('password').value;if(mode==='login'){const {error}=await db.auth.signInWithPassword({email,password});$('authMessage').textContent=error?error.message:'Logged in!';}else{const username=$('username').value.trim().toLowerCase(),displayName=$('displayName').value.trim()||username;if(!/^[a-z0-9_]{3,24}$/.test(username)){ $('authMessage').textContent='Username must be 3–24 characters using letters, numbers, or underscores.';return;}const {error}=await db.auth.signUp({email,password,options:{data:{username,display_name:displayName}}});$('authMessage').textContent=error?error.message:'Account created. Check your email if confirmation is enabled.';}}
async function createPost(){if(!session)return;const caption=$('caption').value.trim(),file=$('mediaFile').files[0];if(!caption&&!file){alert('Add a caption or choose a photo/video.');return;}if(file&&(file.size>MAX_FILE_SIZE||!ALLOWED.includes(file.type))){alert(file.size>MAX_FILE_SIZE?'Maximum file size is 50 MB.':'Unsupported file type.');return;}const btn=$('postButton');btn.disabled=true;setUploadStatus(true,'Preparing…',5);try{let media_url=null,media_type='text';if(file){media_type=file.type.startsWith('image/')?'image':'video';setUploadStatus(true,`Uploading ${media_type}…`,20);const ext=(file.name.split('.').pop()||'bin').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`${session.user.id}/${crypto.randomUUID()}.${ext}`;const {data,error}=await db.storage.from('media').upload(path,file,{contentType:file.type,cacheControl:'3600',upsert:false});if(error)throw error;media_url=db.storage.from('media').getPublicUrl(data.path).data.publicUrl;}const {error}=await db.from('posts').insert({user_id:session.user.id,caption,media_type,media_url});if(error)throw error;$('caption').value='';$('mediaFile').value='';$('fileName').textContent='No file selected';setUploadStatus(true,'Posted! 🎭',100);await loadFeed();setTimeout(()=>setUploadStatus(false),800);}catch(e){setUploadStatus(true,e.message||'Upload failed',0);setTimeout(()=>setUploadStatus(false),2500);}finally{btn.disabled=false;}}
function setUploadStatus(show,text,p){$('uploadStatus').classList.toggle('hidden',!show);$('uploadText').textContent=text;$('uploadProgress').style.width=`${Math.max(0,Math.min(100,p))}%`;}
async function getPosts(limit=100){const {data,error}=await db.from('posts').select('id,user_id,caption,media_url,media_type,created_at,profiles(username,display_name,avatar_url),likes(user_id,created_at),comments(id,user_id,parent_id,body,created_at,profiles(username,display_name),comment_likes(user_id)),reposts(user_id,created_at,profiles(username,display_name))').order('created_at',{ascending:false}).limit(limit);if(error)throw error;return data||[];}
function freshness(t){const h=Math.max(0,(Date.now()-new Date(t).getTime())/3600000);return Math.max(0,72-h)/6;}
function score(p){return (p.likes?.length||0)*3+(p.comments?.length||0)*5+(p.reposts?.length||0)*4+freshness(p.created_at)+(session&&p.user_id===session.user.id?1:0);}
async function loadFeed(){const feed=$('feed');feed.innerHTML='<div class="loading">Loading…</div>';try{if(feedMode==='notifications'){await renderNotifications(feed);return;}if(feedMode==='favorites'){await renderFavorites(feed);return;}let posts=await getPosts(100);if(feedMode==='following'&&session){const {data:f}=await db.from('follows').select('following_id').eq('follower_id',session.user.id);const ids=new Set((f||[]).map(x=>x.following_id));posts=posts.filter(p=>ids.has(p.user_id));}if(feedMode==='fyp')posts.sort((a,b)=>score(b)-score(a));if(feedMode==='trending')posts.sort((a,b)=>score(b)-score(a));if(!posts.length){feed.innerHTML='<div class="loading">No posts yet. Be the first LARPer to post! 🎭</div>';return;}feed.innerHTML=posts.slice(0,30).map(renderPost).join('');bindFeedActions();}catch(e){feed.innerHTML=`<div class="loading">Could not load posts: ${escapeHtml(e.message)}</div>`;}}
function renderPost(p){const pr=p.profiles||{},likes=p.likes||[],comments=p.comments||[],reposts=p.reposts||[],liked=!!session&&likes.some(x=>x.user_id===session.user.id),reposted=!!session&&reposts.some(x=>x.user_id===session.user.id);let media='';if(p.media_type==='image'&&p.media_url)media=`<img class="postMedia" src="${escapeAttr(p.media_url)}" alt="LarpTok post image" loading="lazy">`;if(p.media_type==='video'&&p.media_url)media=`<video class="postMedia" src="${escapeAttr(p.media_url)}" controls playsinline preload="metadata"></video>`;const roots=comments.filter(c=>!c.parent_id),avatar=(pr.display_name||pr.username||'?').slice(0,1).toUpperCase();return `<article class="post" id="post-${p.id}"><div class="postHead"><div class="avatar">${escapeHtml(avatar)}</div><div><div class="name">${escapeHtml(pr.display_name||pr.username||'LARPer')}</div><div class="handle">@${escapeHtml(pr.username||'user')} · ${timeAgo(p.created_at)}</div></div>${session&&session.user.id!==p.user_id?`<button class="ghost followBtn" data-follow="${p.user_id}">Follow</button>`:''}</div>${reposts.length?`<div class="repostInfo">🔁 Reposted by ${reposts.slice(-2).map(r=>`@${escapeHtml(r.profiles?.username||'user')}`).join(', ')}</div>`:''}${media}<div class="postBody">${renderCaption(p.caption||'')}</div><div class="actions"><button class="action ${liked?'liked':''}" data-like="${p.id}">♥ ${likes.length}</button><button class="action ${reposted?'reposted':''}" data-repost="${p.id}">🔁 ${reposts.length}</button><button class="action" data-favorite="${p.id}">⭐ Save</button><button class="action" onclick="sharePost('${escapeAttr(p.id)}')">↗ Share</button><button class="action" data-comments-toggle="${p.id}">💬 ${comments.length}</button></div><div class="comments" id="comments-${p.id}">${roots.slice(-5).map(c=>renderComment(c,comments,p.id)).join('')}</div><form class="commentBox" data-comment-form="${p.id}"><input placeholder="Add a comment… use @username" maxlength="1000" ${session?'':'disabled'}><button class="primary" ${session?'':'disabled'}>Post</button></form></article>`;}
function renderComment(c,all,postId,depth=0){const liked=session&&(c.comment_likes||[]).some(x=>x.user_id===session.user.id),replies=all.filter(x=>x.parent_id===c.id);return `<div class="comment" style="margin-left:${Math.min(depth,3)*18}px"><b>@${escapeHtml(c.profiles?.username||'user')}</b> ${renderCaption(c.body||'')} <div class="commentActions"><button class="action ${liked?'liked':''}" data-comment-like="${c.id}">♥ ${(c.comment_likes||[]).length}</button><button class="action" data-reply="${c.id}" data-post="${postId}">Reply</button></div>${replies.map(r=>renderComment(r,all,postId,depth+1)).join('')}</div>`;}
function renderCaption(text){return escapeHtml(text).replace(/(^|\s)#([a-zA-Z0-9_]{1,50})/g,'$1<a href="#" class="hashtag" data-hashtag="$2">#$2</a>').replace(/(^|\s)@([a-zA-Z0-9_]{3,24})/g,'$1<a href="#" class="mention" data-mention="$2">@$2</a>');}
function bindFeedActions(){const r=$('feed');r.querySelectorAll('[data-like]').forEach(b=>b.onclick=()=>toggleLike(+b.dataset.like));r.querySelectorAll('[data-repost]').forEach(b=>b.onclick=()=>toggleRepost(+b.dataset.repost));r.querySelectorAll('[data-favorite]').forEach(b=>b.onclick=()=>toggleFavorite(+b.dataset.favorite));r.querySelectorAll('[data-follow]').forEach(b=>b.onclick=()=>toggleFollow(b.dataset.follow));r.querySelectorAll('[data-comment-form]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();await addComment(+f.dataset.commentForm,f.querySelector('input').value);});r.querySelectorAll('[data-comment-like]').forEach(b=>b.onclick=()=>toggleCommentLike(+b.dataset.commentLike));r.querySelectorAll('[data-reply]').forEach(b=>b.onclick=()=>replyTo(+b.dataset.reply,+b.dataset.post));r.querySelectorAll('[data-hashtag]').forEach(a=>a.onclick=e=>{e.preventDefault();openHashtag(a.dataset.hashtag);});r.querySelectorAll('[data-mention]').forEach(a=>a.onclick=e=>{e.preventDefault();searchUserPosts(a.dataset.mention);});}
async function toggleLike(id){if(!requireAuth())return;const {data}=await db.from('likes').select('post_id').eq('post_id',id).eq('user_id',session.user.id).maybeSingle();if(data)await db.from('likes').delete().eq('post_id',id).eq('user_id',session.user.id);else await db.from('likes').insert({post_id:id,user_id:session.user.id});loadFeed();}
async function toggleRepost(id){if(!requireAuth())return;const {data}=await db.from('reposts').select('post_id').eq('post_id',id).eq('user_id',session.user.id).maybeSingle();if(data)await db.from('reposts').delete().eq('post_id',id).eq('user_id',session.user.id);else await db.from('reposts').insert({post_id:id,user_id:session.user.id});loadFeed();}
async function toggleFavorite(id){if(!requireAuth())return;const {data}=await db.from('favorites').select('post_id').eq('post_id',id).eq('user_id',session.user.id).maybeSingle();if(data)await db.from('favorites').delete().eq('post_id',id).eq('user_id',session.user.id);else await db.from('favorites').insert({post_id:id,user_id:session.user.id});alert(data?'Removed from saved':'Saved ⭐');}
async function toggleFollow(id){if(!requireAuth())return;const {data}=await db.from('follows').select('follower_id').eq('follower_id',session.user.id).eq('following_id',id).maybeSingle();if(data)await db.from('follows').delete().eq('follower_id',session.user.id).eq('following_id',id);else await db.from('follows').insert({follower_id:session.user.id,following_id:id});loadFeed();}
async function addComment(postId,body,parentId=null){if(!requireAuth()||!body.trim())return;const {data,error}=await db.from('comments').insert({post_id:postId,user_id:session.user.id,body:body.trim(),parent_id:parentId}).select('id').single();if(error)alert(error.message);else{await notifyMentioned(body,postId,data.id);loadFeed();}}
async function replyTo(commentId,postId){if(!requireAuth())return;const body=prompt('Write your reply:');if(body)await addComment(postId,body,commentId);}
async function toggleCommentLike(id){if(!requireAuth())return;const {data}=await db.from('comment_likes').select('comment_id').eq('comment_id',id).eq('user_id',session.user.id).maybeSingle();if(data)await db.from('comment_likes').delete().eq('comment_id',id).eq('user_id',session.user.id);else await db.from('comment_likes').insert({comment_id:id,user_id:session.user.id});loadFeed();}
async function notifyMentioned(text,postId,commentId){const names=[...String(text).matchAll(/@([a-zA-Z0-9_]{3,24})/g)].map(m=>m[1].toLowerCase());if(!names.length)return;const {data}=await db.from('profiles').select('id,username').in('username',names);for(const p of data||[])if(p.id!==session.user.id)await db.from('notifications').insert({recipient_id:p.id,actor_id:session.user.id,type:'mention',post_id:postId,comment_id:commentId});}
async function sharePost(id){const url=`${location.origin}${location.pathname}#post-${id}`;try{await navigator.clipboard.writeText(url);alert('Post link copied!');}catch{prompt('Copy this link:',url);}}
async function renderFavorites(feed){if(!session){feed.innerHTML='<div class="loading">Log in to see saved posts.</div>';return;}const {data,error}=await db.from('favorites').select('post_id').eq('user_id',session.user.id).order('created_at',{ascending:false});if(error)throw error;const ids=(data||[]).map(x=>x.post_id);if(!ids.length){feed.innerHTML='<div class="loading">No saved posts yet. ⭐</div>';return;}const posts=await getPosts(200);const map=new Map(posts.map(p=>[p.id,p]));feed.innerHTML=ids.map(id=>map.get(id)).filter(Boolean).map(renderPost).join('')||'<div class="loading">Your saved posts are not in the current feed window.</div>';bindFeedActions();}
async function renderNotifications(feed){if(!session){feed.innerHTML='<div class="loading">Log in to see notifications.</div>';return;}const {data,error}=await db.from('notifications').select('id,type,post_id,comment_id,created_at,read_at,actor_id,profiles!notifications_actor_id_fkey(username,display_name)').eq('recipient_id',session.user.id).order('created_at',{ascending:false}).limit(50);if(error){feed.innerHTML=`<div class="loading">Could not load notifications: ${escapeHtml(error.message)}</div>`;return;}feed.innerHTML=`<div class="panel notificationPanel"><div class="sectionHeader"><h2>🔔 Notifications</h2><button class="ghost" id="markRead">Mark all read</button></div>${(data||[]).map(n=>`<div class="notification ${n.read_at?'':'unread'}" data-notification="${n.id}"><b>${notificationText(n)}</b><span>${timeAgo(n.created_at)}</span></div>`).join('')||'<div class="loading">You’re all caught up! 🎉</div>'}</div>`;document.querySelectorAll('[data-notification]').forEach(x=>x.onclick=()=>markNotification(+x.dataset.notification));$('markRead')?.addEventListener('click',markAllRead);}
function notificationText(n){const a=n.profiles?.display_name||n.profiles?.username||'Someone';return `${a} ${n.type==='like'?'liked your post':n.type==='follow'?'followed you':n.type==='comment'?'commented on your post':n.type==='reply'?'replied to your comment':n.type==='mention'?'mentioned you':n.type==='repost'?'reposted your post':'interacted with you'}.`;}
async function markNotification(id){await db.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id).eq('recipient_id',session.user.id);renderNotifications($('feed'));}
async function markAllRead(){await db.from('notifications').update({read_at:new Date().toISOString()}).eq('recipient_id',session.user.id).is('read_at',null);renderNotifications($('feed'));}
async function runSearch(raw){const q=raw.trim();if(!q)return;currentSearch=q;if(session){await db.from('search_history').insert({user_id:session.user.id,query:q.slice(0,100)});await trimSearchHistory();}resultMode=q.startsWith('#')?'hashtags':'all';$('discovery').classList.remove('hidden');$('feed').classList.add('hidden');document.querySelectorAll('.discoveryTab').forEach(x=>x.classList.toggle('active',x.dataset.result===resultMode));await renderDiscovery();}
async function renderDiscovery(){const results=$('discoveryResults');results.innerHTML='<div class="loading">Searching…</div>';try{if(resultMode==='trending'||currentSearch.toLowerCase()==='trending'){ $('discoveryTitle').textContent='Trending on LarpTok';await renderTrending(results);return;}const q=currentSearch.replace(/^[@#]/,'');$('discoveryTitle').textContent=currentSearch.startsWith('#')?`#${q}`:currentSearch.startsWith('@')?`@${q}`:`Results for “${currentSearch}”`;const [users,posts,tags]=await Promise.all([searchUsers(q),searchPosts(currentSearch),searchHashtags(q)]);let html='';if(resultMode==='all'||resultMode==='users')html+=renderUserResults(users);if(resultMode==='all'||resultMode==='posts')html+=renderSearchPostResults(posts);if(resultMode==='all'||resultMode==='hashtags')html+=renderHashtagResults(tags);results.innerHTML=html||'<div class="emptyState">No results found.</div>';bindDiscoveryActions();}catch(e){results.innerHTML=`<div class="emptyState">Search failed: ${escapeHtml(e.message)}</div>`;}}
async function searchUsers(q){const safe=escapeLike(q);const {data,error}=await db.from('profiles').select('id,username,display_name,bio,avatar_url').or(`username.ilike.%${safe}%,display_name.ilike.%${safe}%`).order('username').limit(20);if(error)throw error;return data||[];}
async function searchPosts(q){const safe=escapeLike(q.replace(/^[@#]/,''));const {data,error}=await db.from('posts').select('id,user_id,caption,media_url,media_type,created_at,profiles(username,display_name,avatar_url),likes(user_id),comments(id,user_id,parent_id,body,created_at,profiles(username),comment_likes(user_id)),reposts(user_id,created_at,profiles(username))').ilike('caption',`%${safe}%`).order('created_at',{ascending:false}).limit(30);if(error)throw error;return data||[];}
async function searchHashtags(q){const {data,error}=await db.from('hashtags').select('id,name,created_at,post_hashtags(post_id)').ilike('name',`${escapeLike(q)}%`).order('name').limit(30);if(error)throw error;return data||[];}
function renderUserResults(u){if(!u.length)return '';return `<section class="resultSection"><div class="resultTitle">👤 Users</div>${u.map(x=>`<button class="userResult" onclick="searchUserPosts('${escapeAttr(x.username)}')"><div class="avatar">${escapeHtml((x.display_name||x.username).slice(0,1).toUpperCase())}</div><div><b>${escapeHtml(x.display_name||x.username)}</b><span>@${escapeHtml(x.username)}</span><small>${escapeHtml(x.bio||'')}</small></div></button>`).join('')}</section>`;}
function renderSearchPostResults(p){if(!p.length)return '';return `<section class="resultSection"><div class="resultTitle">🎬 Posts</div>${p.slice(0,12).map(renderPost).join('')}</section>`;}
function renderHashtagResults(t){if(!t.length)return '';return `<section class="resultSection"><div class="resultTitle">#️⃣ Hashtags</div>${t.map(x=>`<button class="hashtagResult" onclick="openHashtag('${escapeAttr(x.name)}')"><b>#${escapeHtml(x.name)}</b><span>${x.post_hashtags?.length||0} posts</span></button>`).join('')}</section>`;}
async function renderTrending(el){const posts=await getPosts(100);posts.sort((a,b)=>score(b)-score(a));const tags=await db.from('hashtags').select('name,post_hashtags(post_id)').limit(30);el.innerHTML=`<section class="resultSection"><div class="resultTitle">🔥 Trending posts</div>${posts.slice(0,10).map(renderPost).join('')}</section><section class="resultSection"><div class="resultTitle">#️⃣ Trending hashtags</div>${(tags.data||[]).sort((a,b)=>(b.post_hashtags?.length||0)-(a.post_hashtags?.length||0)).slice(0,10).map(x=>`<button class="hashtagResult" onclick="openHashtag('${escapeAttr(x.name)}')"><b>#${escapeHtml(x.name)}</b><span>${x.post_hashtags?.length||0} posts</span></button>`).join('')}</section>`;bindDiscoveryActions();}
async function openHashtag(name){currentSearch='#'+name;resultMode='posts';$('discovery').classList.remove('hidden');$('feed').classList.add('hidden');const {data:tag,error}=await db.from('hashtags').select('id').eq('name',name.toLowerCase()).single();if(error){$('discoveryResults').innerHTML='<div class="emptyState">Hashtag not found.</div>';return;}const {data:links}=await db.from('post_hashtags').select('post_id').eq('hashtag_id',tag.id);const ids=(links||[]).map(x=>x.post_id);const posts=await getPosts(200);const byId=new Map(posts.map(p=>[p.id,p]));$('discoveryTitle').textContent='#'+name;$('discoveryResults').innerHTML=ids.map(id=>byId.get(id)).filter(Boolean).map(renderPost).join('')||'<div class="emptyState">No posts with this hashtag yet.</div>';bindFeedActions();}
async function searchUserPosts(username){currentSearch='@'+username;const {data:user}=await db.from('profiles').select('id,username,display_name,bio').eq('username',username).single();if(!user)return;const posts=await getPosts(200);const mine=posts.filter(p=>p.user_id===user.id);$('discovery').classList.remove('hidden');$('feed').classList.add('hidden');$('discoveryTitle').textContent='@'+username;$('discoveryResults').innerHTML=`<section class="profileResult"><div class="avatar">${escapeHtml((user.display_name||username).slice(0,1).toUpperCase())}</div><h2>${escapeHtml(user.display_name||username)}</h2><p>@${escapeHtml(username)}</p><p>${escapeHtml(user.bio||'')}</p></section>${mine.map(renderPost).join('')||'<div class="emptyState">No posts yet.</div>'}`;bindFeedActions();}
function bindDiscoveryActions(){const r=$('discoveryResults');r.querySelectorAll('[data-like]').forEach(b=>b.onclick=()=>toggleLike(+b.dataset.like));r.querySelectorAll('[data-repost]').forEach(b=>b.onclick=()=>toggleRepost(+b.dataset.repost));r.querySelectorAll('[data-favorite]').forEach(b=>b.onclick=()=>toggleFavorite(+b.dataset.favorite));r.querySelectorAll('[data-follow]').forEach(b=>b.onclick=()=>toggleFollow(b.dataset.follow));r.querySelectorAll('[data-comment-form]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();await addComment(+f.dataset.commentForm,f.querySelector('input').value);});r.querySelectorAll('[data-hashtag]').forEach(a=>a.onclick=e=>{e.preventDefault();openHashtag(a.dataset.hashtag);});r.querySelectorAll('[data-mention]').forEach(a=>a.onclick=e=>{e.preventDefault();searchUserPosts(a.dataset.mention);});}
async function loadSearchHistory(){if(!session)return;const {data}=await db.from('search_history').select('id,query,created_at').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(8);$('searchHistory').innerHTML=(data||[]).map(x=>`<button class="historyItem" onclick="runSearch('${escapeAttr(x.query)}')">${escapeHtml(x.query)}</button>`).join('')+(data?.length?'<button class="linkButton" onclick="clearSearchHistory()">Clear history</button>':'');}
async function trimSearchHistory(){if(!session)return;const {data}=await db.from('search_history').select('id').eq('user_id',session.user.id).order('created_at',{ascending:false}).range(8,1000);for(const x of data||[])await db.from('search_history').delete().eq('id',x.id);}
async function clearSearchHistory(){if(session)await db.from('search_history').delete().eq('user_id',session.user.id);loadSearchHistory();}
function closeDiscovery(){$('discovery').classList.add('hidden');$('feed').classList.remove('hidden');loadFeed();}
function requireAuth(){if(session)return true;$('authPanel').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});return false;}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function escapeAttr(s){return escapeHtml(s).replace(/`/g,'&#96;');}
function escapeLike(s){return String(s).replace(/[%,_\\]/g,m=>'\\'+m).replace(/,/g,'');}
function timeAgo(t){const sec=Math.max(0,(Date.now()-new Date(t).getTime())/1000);if(sec<60)return'now';if(sec<3600)return`${Math.floor(sec/60)}m`;if(sec<86400)return`${Math.floor(sec/3600)}h`;return`${Math.floor(sec/86400)}d`;}
function formatBytes(n){if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;return`${(n/1048576).toFixed(1)} MB`;}
init();