(() => {
  const creator={open:false,tab:'overview',profile:null,posts:[],playlists:[],drafts:[],session:null};
  const db=window.supabase.createClient('https://rphsmqppmqvqzfpcablw.supabase.co','sb_publishable_vB7G9y3xTKk0swxKAbaIHQ_Gt1tshVw');
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const fmt=n=>new Intl.NumberFormat().format(n||0);
  const pct=(n,d)=>d?`${Math.round(n/d*100)}%`:'0%';
  const ago=d=>{const s=Math.max(0,(Date.now()-new Date(d).getTime())/1000);if(s<60)return'just now';if(s<3600)return`${Math.floor(s/60)}m ago`;if(s<86400)return`${Math.floor(s/3600)}h ago`;return`${Math.floor(s/86400)}d ago`;};
  function user(){return creator.session?.user||null;}
  async function syncSession(){const r=await db.auth.getSession();creator.session=r.data.session;return creator.session;}
  function show(){if(!user()){alert('Log in to open Creator Center.');return;}$('creatorPanel')?.classList.remove('hidden');creator.open=true;loadDashboard();}
  function hide(){$('creatorPanel')?.classList.add('hidden');creator.open=false;}
  async function loadDashboard(){const u=await syncSession();if(!u)return;$('creatorResults').innerHTML='<div class="loading">Loading your creator data…</div>';try{const [p,ps,f,pl,d]=await Promise.all([db.from('profiles').select('*').eq('id',u.id).single(),db.from('posts').select('id,caption,media_url,media_type,created_at,is_public,allow_comments').eq('user_id',u.id).order('created_at',{ascending:false}),db.from('follows').select('follower_id,created_at').eq('following_id',u.id),db.from('playlists').select('id,name,description,is_public,created_at,playlist_posts(post_id,position)').eq('user_id',u.id).order('created_at',{ascending:false}),db.from('drafts').select('*').eq('user_id',u.id).order('updated_at',{ascending:false})]);if(p.error)throw p.error;creator.profile=p.data;creator.posts=ps.data||[];creator.followers=f.data||[];creator.playlists=pl.data||[];creator.drafts=d.data||[];creator.analytics=await analytics();render();}catch(e){$('creatorResults').innerHTML=`<div class="emptyState">Creator Center failed: ${esc(e.message)}</div>`;}}
  async function analytics(){const ids=creator.posts.map(p=>p.id);if(!ids.length)return{views:0,likes:0,comments:0,reposts:0,favorites:0,shares:0,engagement:0,rows:[]};const [v,l,c,r,f,s]=await Promise.all([db.from('post_views').select('post_id').in('post_id',ids),db.from('likes').select('post_id').in('post_id',ids),db.from('comments').select('post_id').in('post_id',ids),db.from('reposts').select('post_id').in('post_id',ids),db.from('favorites').select('post_id').in('post_id',ids),db.from('post_shares').select('post_id').in('post_id',ids)]);const g={};creator.posts.forEach(p=>g[p.id]={post:p,views:0,likes:0,comments:0,reposts:0,favorites:0,shares:0});for(const x of v.data||[])g[x.post_id]&&(g[x.post_id].views++);for(const x of l.data||[])g[x.post_id]&&(g[x.post_id].likes++);for(const x of c.data||[])g[x.post_id]&&(g[x.post_id].comments++);for(const x of r.data||[])g[x.post_id]&&(g[x.post_id].reposts++);for(const x of f.data||[])g[x.post_id]&&(g[x.post_id].favorites++);for(const x of s.data||[])g[x.post_id]&&(g[x.post_id].shares++);const rows=Object.values(g).sort((a,b)=>(b.likes+b.comments+b.reposts+b.favorites+b.shares)-(a.likes+a.comments+a.reposts+a.favorites+a.shares));const sum=k=>rows.reduce((n,x)=>n+x[k],0);const likes=sum('likes'),comments=sum('comments'),reposts=sum('reposts'),favorites=sum('favorites'),shares=sum('shares'),views=sum('views');return{views,likes,comments,reposts,favorites,shares,engagement:likes+comments+reposts+favorites+shares,rows};}
  function render(){const a=creator.analytics||{};const tabs=['overview','content','playlists','drafts','profile'];$('creatorResults').innerHTML=`<div class="creatorTabs">${tabs.map(t=>`<button class="creatorTab ${creator.tab===t?'active':''}" data-ctab="${t}">${({overview:'📊 Overview',content:'🎬 Content',playlists:'📋 Playlists',drafts:'📝 Drafts',profile:'👤 Profile'})[t]}</button>`).join('')}</div><div id="creatorBody"></div>`;document.querySelectorAll('[data-ctab]').forEach(b=>b.onclick=()=>{creator.tab=b.dataset.ctab;render();});const body=$('creatorBody');if(creator.tab==='overview')body.innerHTML=overview(a);if(creator.tab==='content')body.innerHTML=content(a);if(creator.tab==='playlists')body.innerHTML=playlists();if(creator.tab==='drafts')body.innerHTML=drafts();if(creator.tab==='profile')body.innerHTML=profile();bind();}
  function overview(a){return`<div class="creatorGrid">${[['👀','Views',a.views],['❤️','Likes',a.likes],['💬','Comments',a.comments],['🔁','Reposts',a.reposts],['⭐','Favorites',a.favorites],['📤','Shares',a.shares],['👥','Followers',creator.followers.length],['📈','Engagement',a.engagement]].map(x=>`<div class="metric"><span>${x[0]}</span><b>${fmt(x[2])}</b><small>${x[1]}</small></div>`).join('')}</div><section class="creatorCard"><h3>Top-performing posts</h3>${(a.rows||[]).slice(0,8).map(row).join('')||'<div class="muted">Create a post to start seeing analytics.</div>'}</section>`;}
  function row(r){return`<div class="analyticsRow"><div class="analyticsThumb">${r.post.media_url?(r.post.media_type==='video'?'<span>▶️</span>':`<img src="${esc(r.post.media_url)}" alt="">`):'🎭'}</div><div class="analyticsInfo"><b>${esc((r.post.caption||'Untitled post').slice(0,70))}</b><small>${ago(r.post.created_at)}</small></div><div class="analyticsStats">👀 ${fmt(r.views)} · ❤️ ${fmt(r.likes)} · 💬 ${fmt(r.comments)} · 🔁 ${fmt(r.reposts)} · ⭐ ${fmt(r.favorites)} · 📤 ${fmt(r.shares)}<br><small>Engagement ${pct(r.likes+r.comments+r.reposts+r.favorites+r.shares,Math.max(1,r.views))}</small></div></div>`;}
  function content(a){return`<div class="creatorCard"><div class="sectionHeader"><div><h3>Your content</h3><p class="muted">Per-post analytics plus editing and privacy controls.</p></div><button class="primary" id="refreshCreator">Refresh</button></div>${(a.rows||[]).map(r=>`<div class="contentRow">${row(r)}<div class="contentButtons"><button class="ghost" data-edit="${r.post.id}">Edit</button><button class="ghost" data-delete="${r.post.id}">Delete</button><button class="ghost" data-privacy="${r.post.id}">${r.post.is_public?'Public':'Private'}</button><button class="ghost" data-comments="${r.post.id}">${r.post.allow_comments?'Comments on':'Comments off'}</button></div></div>`).join('')||'<div class="emptyState">No posts yet.</div>'}</div>`;}
  function playlists(){return`<div class="creatorCard"><div class="sectionHeader"><div><h3>Playlists</h3><p class="muted">Create collections and add/remove your posts.</p></div><button class="primary" id="newPlaylist">＋ New playlist</button></div>${creator.playlists.map(p=>`<div class="playlistRow"><div><b>${esc(p.name)}</b><small>${p.is_public?'Public':'Private'} · ${p.playlist_posts?.length||0} posts</small></div><div class="contentButtons"><button class="ghost" data-playadd="${p.id}">Add post</button><button class="ghost" data-playremove="${p.id}">Remove post</button><button class="ghost" data-playedit="${p.id}">Rename</button><button class="ghost" data-playprivacy="${p.id}">${p.is_public?'Public':'Private'}</button><button class="ghost" data-playdelete="${p.id}">Delete</button></div></div>`).join('')||'<div class="emptyState">No playlists yet.</div>'}</div>`;}
  function drafts(){return`<div class="creatorCard"><div class="sectionHeader"><div><h3>Drafts</h3><p class="muted">Unfinished captions stay private.</p></div><button class="primary" id="newDraft">＋ New draft</button></div>${creator.drafts.map(d=>`<div class="playlistRow"><div><b>${esc((d.caption||'Empty draft').slice(0,70))}</b><small>Updated ${ago(d.updated_at)}</small></div><div><button class="ghost" data-draftload="${d.id}">Load</button><button class="ghost" data-draftdelete="${d.id}">Delete</button></div></div>`).join('')||'<div class="emptyState">No drafts yet.</div>'}</div>`;}
  function profile(){const p=creator.profile||{};return`<div class="creatorCard"><h3>Profile customization</h3><form id="profileForm" class="creatorForm"><label>Display name<input id="cpDisplay" maxlength="40" value="${esc(p.display_name||'')}"></label><label>Username<input id="cpUsername" maxlength="24" value="${esc(p.username||'')}"></label><label>Bio<textarea id="cpBio" maxlength="160">${esc(p.bio||'')}</textarea></label><label>Website<input id="cpWebsite" type="url" maxlength="200" value="${esc(p.website_url||'')}"></label><label class="check"><input id="cpPrivate" type="checkbox" ${p.is_private?'checked':''}> Private account</label><button class="primary">Save profile</button><p id="profileMsg" class="muted"></p></form></div>`;}
  function bind(){
    $('refreshCreator')?.addEventListener('click',loadDashboard);$('newPlaylist')?.addEventListener('click',createPlaylist);$('newDraft')?.addEventListener('click',createDraft);$('profileForm')?.addEventListener('submit',saveProfile);
    document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editPost(+b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deletePost(+b.dataset.delete));document.querySelectorAll('[data-privacy]').forEach(b=>b.onclick=()=>togglePost(+b.dataset.privacy,'is_public'));document.querySelectorAll('[data-comments]').forEach(b=>b.onclick=()=>togglePost(+b.dataset.comments,'allow_comments'));
    document.querySelectorAll('[data-playadd]').forEach(b=>b.onclick=()=>addToPlaylist(+b.dataset.playadd));document.querySelectorAll('[data-playremove]').forEach(b=>b.onclick=()=>removeFromPlaylist(+b.dataset.playremove));document.querySelectorAll('[data-playedit]').forEach(b=>b.onclick=()=>renamePlaylist(+b.dataset.playedit));document.querySelectorAll('[data-playprivacy]').forEach(b=>b.onclick=()=>togglePlaylistPrivacy(+b.dataset.playprivacy));document.querySelectorAll('[data-playdelete]').forEach(b=>b.onclick=()=>deletePlaylist(+b.dataset.playdelete));
    document.querySelectorAll('[data-draftload]').forEach(b=>b.onclick=()=>loadDraft(+b.dataset.draftload));document.querySelectorAll('[data-draftdelete]').forEach(b=>b.onclick=()=>deleteDraft(+b.dataset.draftdelete));
  }
  async function editPost(id){const p=creator.posts.find(x=>x.id===id);const text=prompt('Edit caption:',p?.caption||'');if(text===null)return;const{error}=await db.from('posts').update({caption:text}).eq('id',id).eq('user_id',user().id);if(error)alert(error.message);else loadDashboard();}
  async function deletePost(id){if(!confirm('Delete this post permanently?'))return;const{error}=await db.from('posts').delete().eq('id',id).eq('user_id',user().id);if(error)alert(error.message);else loadDashboard();}
  async function togglePost(id,field){const p=creator.posts.find(x=>x.id===id);if(!p)return;const patch={};patch[field]=!p[field];const{error}=await db.from('posts').update(patch).eq('id',id).eq('user_id',user().id);if(error)alert(error.message);else loadDashboard();}
  async function createPlaylist(){const name=prompt('Playlist name:');if(!name?.trim())return;const{error}=await db.from('playlists').insert({user_id:user().id,name:name.trim(),is_public:true});if(error)alert(error.message);else loadDashboard();}
  async function renamePlaylist(id){const p=creator.playlists.find(x=>x.id===id);const name=prompt('New playlist name:',p?.name||'');if(!name?.trim())return;const{error}=await db.from('playlists').update({name:name.trim(),updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',user().id);if(error)alert(error.message);else loadDashboard();}
  async function togglePlaylistPrivacy(id){const p=creator.playlists.find(x=>x.id===id);if(!p)return;const{error}=await db.from('playlists').update({is_public:!p.is_public,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',user().id);if(error)alert(error.message);else loadDashboard();}
  async function deletePlaylist(id){if(!confirm('Delete this playlist? Posts will not be deleted.'))return;const{error}=await db.from('playlists').delete().eq('id',id).eq('user_id',user().id);if(error)alert(error.message);else loadDashboard();}
  async function addToPlaylist(id){const p=creator.playlists.find(x=>x.id===id);if(!p)return;const raw=prompt(`Post ID to add to “${p.name}”:\nYour post IDs: ${(creator.posts||[]).slice(0,12).map(x=>x.id).join(', ')}`);const postId=Number(raw);if(!creator.posts.some(x=>x.id===postId)){alert('Enter one of your post IDs.');return;}const position=(p.playlist_posts||[]).length;const{error}=await db.from('playlist_posts').upsert({playlist_id:id,post_id:postId,position});if(error)alert(error.message);else loadDashboard();}
  async function removeFromPlaylist(id){const p=creator.playlists.find(x=>x.id===id);if(!p)return;const raw=prompt(`Post ID to remove:\nCurrent IDs: ${(p.playlist_posts||[]).map(x=>x.post_id).join(', ')}`);const postId=Number(raw);if(!postId)return;const{error}=await db.from('playlist_posts').delete().eq('playlist_id',id).eq('post_id',postId);if(error)alert(error.message);else loadDashboard();}
  async function createDraft(){const caption=prompt('Draft caption:','');const{error}=await db.from('drafts').insert({user_id:user().id,caption:caption||''});if(error)alert(error.message);else loadDashboard();}
  async function loadDraft(id){const d=creator.drafts.find(x=>x.id===id);if(!d)return;hide();if($('caption')){$('caption').value=d.caption||'';window.scrollTo({top:$('caption').closest('.composer')?.offsetTop||0,behavior:'smooth'});alert('Draft loaded into the composer.');}}
  async function deleteDraft(id){if(!confirm('Delete this draft?'))return;const{error}=await db.from('drafts').delete().eq('id',id).eq('user_id',user().id);if(error)alert(error.message);else loadDashboard();}
  async function saveProfile(e){e.preventDefault();const u=user();const p={display_name:$('cpDisplay').value.trim(),username:$('cpUsername').value.trim().toLowerCase(),bio:$('cpBio').value.trim(),website_url:$('cpWebsite').value.trim()||null,is_private:$('cpPrivate').checked};if(!/^[a-z0-9_]{3,24}$/.test(p.username)){ $('profileMsg').textContent='Username must be 3–24 characters using letters, numbers, or underscores.';return;}const{error}=await db.from('profiles').update(p).eq('id',u.id);$('profileMsg').textContent=error?error.message:'Profile saved!';if(!error)loadDashboard();}
  async function trackViews(){const feed=$('feed');if(!feed||!window.IntersectionObserver)return;const seen=new Set();const io=new IntersectionObserver(es=>es.forEach(async e=>{if(!e.isIntersecting||e.intersectionRatio<.6)return;const id=Number(e.target.id.replace('post-',''));if(!id||seen.has(id))return;seen.add(id);await db.from('post_views').insert({post_id:id,viewer_id:user()?.id||null});}),{threshold:.6});feed.querySelectorAll('.post[id^="post-"]').forEach(x=>io.observe(x));}
  function watchFeed(){const feed=$('feed');if(!feed)return;new MutationObserver(()=>setTimeout(trackViews,100)).observe(feed,{childList:true,subtree:true});setTimeout(trackViews,300);}
  function install(){db.auth.getSession().then(r=>{creator.session=r.data.session;const b=$('creatorCenterBtn');if(b&&creator.session)b.classList.remove('hidden');});db.auth.onAuthStateChange((_e,s)=>{creator.session=s;const b=$('creatorCenterBtn');if(b)b.classList.toggle('hidden',!s);});$('creatorCenterBtn')?.addEventListener('click',show);$('closeCreator')?.addEventListener('click',hide);$('saveDraftButton')?.addEventListener('click',async()=>{const u=await syncSession();if(!u)return alert('Log in to save drafts.');const caption=$('caption')?.value||'';const{error}=await db.from('drafts').insert({user_id:u.id,caption});if(error)alert(error.message);else alert('Draft saved 📝');});watchFeed();}
  window.LarpTokCreator={show,hide,loadDashboard,trackViews};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();