(() => {
  const state={file:null,video:null,start:0,end:0,speed:1,text:'',sound:null,recorded:null,recording:false};
  const $=id=>document.getElementById(id);
  const db=window.supabase.createClient('https://rphsmqppmqvqzfpcablw.supabase.co','sb_publishable_vB7G9y3xTKk0swxKAbaIHQ_Gt1tshVw');
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  async function session(){return (await db.auth.getSession()).data.session;}
  function open(){const s=$('creationPanel');if(!s)return;s.classList.remove('hidden');loadSounds();window.scrollTo({top:s.offsetTop-10,behavior:'smooth'});}
  function close(){ $('creationPanel')?.classList.add('hidden'); }
  async function loadSounds(){const box=$('soundList');if(!box)return;const r=await db.from('sounds').select('id,title,artist_name,audio_url,duration_seconds').order('created_at',{ascending:false}).limit(30);if(r.error){box.innerHTML='<p class="creationHint">Could not load sounds.</p>';return;}box.innerHTML=(r.data||[]).map(s=>`<div class="soundItem ${state.sound?.id===s.id?'soundSelected':''}"><div><b>${esc(s.title)}</b><small>${esc(s.artist_name||'Original sound')}${s.duration_seconds?` · ${Math.round(s.duration_seconds)}s`:''}</small></div><button class="ghost" data-sound="${s.id}">${state.sound?.id===s.id?'Selected':'Use'}</button></div>`).join('')||'<p class="creationHint">No sounds yet. Create an original sound by uploading audio.</p>';box.querySelectorAll('[data-sound]').forEach(b=>b.onclick=()=>selectSound(Number(b.dataset.sound)));}
  async function selectSound(id){const r=await db.from('sounds').select('*').eq('id',id).single();if(!r.error){state.sound=r.data;loadSounds();}}
  function setup(){
    $('openCreation')?.addEventListener('click',open);$('closeCreation')?.addEventListener('click',close);$('editorFile')?.addEventListener('change',onFile);$('editorText')?.addEventListener('input',e=>{state.text=e.target.value;$('editorOverlay').textContent=state.text;});$('speed')?.addEventListener('input',e=>{state.speed=Number(e.target.value);$('speedValue').textContent=state.speed+'×';if(state.video)state.video.playbackRate=state.speed;});$('startTime')?.addEventListener('input',updateRange);$('endTime')?.addEventListener('input',updateRange);$('previewEditor')?.addEventListener('click',()=>state.video?.play());$('exportEdit')?.addEventListener('click',exportClip);$('useEdit')?.addEventListener('click',useEdited);$('uploadSound')?.addEventListener('change',uploadSound);$('clearEdit')?.addEventListener('click',reset); }
  function onFile(e){const f=e.target.files[0];if(!f)return;if(!f.type.startsWith('video/')){alert('Choose a video file.');return;}if(f.size>50*1024*1024){alert('Maximum video size is 50 MB.');return;}state.file=f;const url=URL.createObjectURL(f);const v=$('editorVideo');v.src=url;state.video=v;v.onloadedmetadata=()=>{state.start=0;state.end=v.duration;$('startTime').max=v.duration;$('endTime').max=v.duration;$('endTime').value=v.duration;$('startValue').textContent='0.0s';$('endValue').textContent=v.duration.toFixed(1)+'s';};v.ontimeupdate=()=>{if(v.currentTime>=state.end)v.currentTime=state.start;};$('editorEmpty').classList.add('hidden');v.classList.remove('hidden');}
  function updateRange(){let a=Number($('startTime').value),b=Number($('endTime').value);if(a>=b-0.1){if(document.activeElement===$('startTime'))a=Math.max(0,b-0.1);else b=Math.min(state.video?.duration||b,a+0.1);}state.start=a;state.end=b;$('startTime').value=a;$('endTime').value=b;$('startValue').textContent=a.toFixed(1)+'s';$('endValue').textContent=b.toFixed(1)+'s';if(state.video)state.video.currentTime=a;}
  function reset(){state.file=null;state.video=null;state.recorded=null;state.text='';state.sound=null;$('editorFile').value='';$('editorText').value='';$('editorOverlay').textContent='';$('editorVideo').classList.add('hidden');$('editorEmpty').classList.remove('hidden');$('editedPreview').classList.add('hidden');$('exportEdit').disabled=false;loadSounds();}
  async function exportClip(){if(!state.video){alert('Choose a video first.');return;}if(!('MediaRecorder' in window)||!HTMLCanvasElement.prototype.captureStream){alert('This browser does not support browser video export. You can still use the trim, speed, text preview, and sound tools.');return;}const v=state.video,canvas=document.createElement('canvas');canvas.width=v.videoWidth||720;canvas.height=v.videoHeight||1280;const ctx=canvas.getContext('2d');const stream=canvas.captureStream(30);try{const source=v.captureStream();source.getAudioTracks().forEach(t=>stream.addTrack(t));}catch{}const mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(x=>MediaRecorder.isTypeSupported(x));if(!mime){alert('Video export is not supported by this browser.');return;}const chunks=[];const rec=new MediaRecorder(stream,{mimeType:mime});rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{state.recorded=new Blob(chunks,{type:mime});const u=URL.createObjectURL(state.recorded);$('editedPreview').src=u;$('editedPreview').classList.remove('hidden');$('exportStatus').textContent='Edited clip ready! 🎬';};rec.start(200);state.recording=true;$('exportEdit').disabled=true;$('exportStatus').textContent='Rendering edited clip…';v.currentTime=state.start;await v.play();const draw=()=>{if(!state.recording)return;ctx.drawImage(v,0,0,canvas.width,canvas.height);if(state.text){ctx.save();ctx.fillStyle='white';ctx.strokeStyle='black';ctx.lineWidth=6;ctx.font=`800 ${Math.max(24,canvas.width/18)}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.strokeText(state.text,canvas.width/2,canvas.height*.78,canvas.width*.9);ctx.fillText(state.text,canvas.width/2,canvas.height*.78,canvas.width*.9);ctx.restore();}if(v.currentTime>=state.end){state.recording=false;v.pause();rec.stop();}else requestAnimationFrame(draw);};v.playbackRate=state.speed;draw();}
  async function useEdited(){if(!state.recorded){alert('Export an edited clip first.');return;}const s=await session();if(!s){alert('Log in first.');return;}const ext='webm',path=`${s.user.id}/${crypto.randomUUID()}.${ext}`;$('exportStatus').textContent='Uploading edited clip…';const up=await db.storage.from('media').upload(path,state.recorded,{contentType:state.recorded.type,upsert:false});if(up.error){alert(up.error.message);return;}const url=db.storage.from('media').getPublicUrl(path).data.publicUrl;const ins=await db.from('posts').insert({user_id:s.user.id,caption:state.text,media_type:'video',media_url:url,edited_media_url:url,overlay_text:state.text,playback_speed:state.speed,sound_id:state.sound?.id||null});if(ins.error){alert(ins.error.message);return;}alert('Edited video posted! 🎭');reset();close();window.dispatchEvent(new Event('larptok-posted'));}
  async function uploadSound(e){const s=await session();const f=e.target.files[0];if(!s||!f)return;if(!f.type.startsWith('audio/')){alert('Choose an audio file.');return;}if(f.size>20*1024*1024){alert('Maximum audio size is 20 MB.');return;}const title=prompt('Sound title:',f.name.replace(/\.[^.]+$/,''));if(!title?.trim())return;const path=`${s.user.id}/sounds/${crypto.randomUUID()}.${(f.name.split('.').pop()||'mp3').replace(/[^a-z0-9]/gi,'')}`;const up=await db.storage.from('media').upload(path,f,{contentType:f.type,upsert:false});if(up.error){alert(up.error.message);return;}const url=db.storage.from('media').getPublicUrl(path).data.publicUrl;const r=await db.from('sounds').insert({creator_id:s.user.id,title:title.trim(),artist_name:'Original sound',audio_url:url}).select().single();if(r.error)alert(r.error.message);else{state.sound=r.data;loadSounds();alert('Original sound added! 🎵');}}
  window.LarpTokCreation={open};document.addEventListener('DOMContentLoaded',setup);
})();