const SUPABASE_URL='https://rphsmqppmqvqzfpcablw.supabase.co';
const SUPABASE_KEY='sb_publishable_vB7G9y3xTKk0swxKAbaIHQ_Gt1tshVw';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let session=null,currentConversation=null;
const $=id=>document.getElementById(id);
async function init(){const {data}=await db.auth.getSession();session=data.session;if(!session){$('authNotice').innerHTML='<p>Please log in on the <a href="index.html">main LarpTok page</a> first.</p>';return;}await loadConversations();db.channel('messages-live').on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},payload=>{if(currentConversation&&payload.new.conversation_id===currentConversation.id)loadMessages();loadConversations();}).subscribe();}
async function loadConversations(){const {data:members}=await db.from('conversation_members').select('conversation_id,last_read_at').eq('user_id',session.user.id);const ids=(members||[]).map(x=>x.conversation_id);if(!ids.length){$('conversations').innerHTML='<p class="muted">No conversations yet.</p>';return;}const {data}=await db.from('conversations').select('id,name,is_group,created_at').in('id',ids).order('created_at',{ascending:false});$('conversations').innerHTML=(data||[]).map(c=>`<button class="conversationItem" data-id="${c.id}">${escapeHtml(c.name||'Conversation')}</button>`).join('');document.querySelectorAll('.conversationItem').forEach(b=>b.onclick=()=>openConversation(b.dataset.id));}
async function openConversation(id){const {data:c}=await db.from('conversations').select('*').eq('id',id).single();if(!c)return;currentConversation=c;$('chatHeader').textContent=c.name||'Conversation';$('sendForm').classList.remove('hidden');await loadMessages();await db.from('conversation_members').update({last_read_at:new Date().toISOString()}).eq('conversation_id',id).eq('user_id',session.user.id);}
async function loadMessages(){const {data,error}=await db.from('messages').select('id,sender_id,body,created_at,profiles(username,display_name)').eq('conversation_id',currentConversation.id).order('created_at',{ascending:true}).limit(200);if(error){$('messages').textContent=error.message;return;}$('messages').innerHTML=(data||[]).map(m=>`<div class="messageBubble ${m.sender_id===session.user.id?'mine':''}"><b>${escapeHtml(m.profiles?.display_name||m.profiles?.username||'User')}</b><div>${escapeHtml(m.body)}</div><small>${new Date(m.created_at).toLocaleString()}</small></div>`).join('');$('messages').scrollTop=$('messages').scrollHeight;}
$('newConversation').onsubmit=async e=>{e.preventDefault();const username=$('userSearch').value.trim().toLowerCase();if(!username||!session)return;const {data:user}=await db.from('profiles').select('id,username,display_name').eq('username',username).maybeSingle();if(!user){alert('User not found.');return;}if(user.id===session.user.id){alert('You cannot message yourself.');return;}const {data:existing}=await db.from('conversation_members').select('conversation_id').eq('user_id',session.user.id);for(const x of existing||[]){const {data:other}=await db.from('conversation_members').select('user_id').eq('conversation_id',x.conversation_id).eq('user_id',user.id).maybeSingle();if(other){openConversation(x.conversation_id);return;}}const {data:c,error}=await db.from('conversations').insert({is_group:false,created_by:session.user.id}).select().single();if(error){alert(error.message);return;}await db.from('conversation_members').insert([{conversation_id:c.id,user_id:session.user.id},{conversation_id:c.id,user_id:user.id}]);$('userSearch').value='';await loadConversations();openConversation(c.id);};
$('sendForm').onsubmit=async e=>{e.preventDefault();const body=$('messageInput').value.trim();if(!body||!currentConversation)return;const {error}=await db.from('messages').insert({conversation_id:currentConversation.id,sender_id:session.user.id,body});if(error)alert(error.message);else{$('messageInput').value='';loadMessages();}};
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
init();