-- LarpTok v0.7 Communication
create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  name text,
  is_group boolean not null default false,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create table if not exists public.conversation_members (
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check (role in ('member','admin')),
  last_read_at timestamptz,
  joined_at timestamptz not null default now(),
  primary key (conversation_id,user_id)
);
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);
create table if not exists public.message_reads (
  message_id bigint not null references public.messages(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key(message_id,user_id)
);
create index if not exists conversation_members_user_idx on public.conversation_members(user_id,conversation_id);
create index if not exists messages_conversation_created_idx on public.messages(conversation_id,created_at desc);
create index if not exists messages_sender_idx on public.messages(sender_id);
create index if not exists message_reads_user_idx on public.message_reads(user_id,read_at desc);
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;
alter table public.message_reads enable row level security;
drop policy if exists "members can view conversations" on public.conversations;
create policy "members can view conversations" on public.conversations for select to authenticated using (exists(select 1 from public.conversation_members cm where cm.conversation_id=id and cm.user_id=auth.uid()));
drop policy if exists "authenticated can create conversations" on public.conversations;
create policy "authenticated can create conversations" on public.conversations for insert to authenticated with check (created_by=auth.uid());
drop policy if exists "members can view members" on public.conversation_members;
create policy "members can view members" on public.conversation_members for select to authenticated using (exists(select 1 from public.conversation_members mine where mine.conversation_id=conversation_id and mine.user_id=auth.uid()));
drop policy if exists "users can add members to own conversations" on public.conversation_members;
create policy "users can add members to own conversations" on public.conversation_members for insert to authenticated with check (user_id=auth.uid() or exists(select 1 from public.conversation_members mine where mine.conversation_id=conversation_id and mine.user_id=auth.uid() and mine.role='admin'));
drop policy if exists "members can update own read state" on public.conversation_members;
create policy "members can update own read state" on public.conversation_members for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
drop policy if exists "members can read messages" on public.messages;
create policy "members can read messages" on public.messages for select to authenticated using (exists(select 1 from public.conversation_members cm where cm.conversation_id=conversation_id and cm.user_id=auth.uid()));
drop policy if exists "members can send messages" on public.messages;
create policy "members can send messages" on public.messages for insert to authenticated with check (sender_id=auth.uid() and exists(select 1 from public.conversation_members cm where cm.conversation_id=conversation_id and cm.user_id=auth.uid()));
drop policy if exists "senders can delete messages" on public.messages;
create policy "senders can delete messages" on public.messages for update to authenticated using (sender_id=auth.uid()) with check (sender_id=auth.uid());
drop policy if exists "members manage message reads" on public.message_reads;
create policy "members manage message reads" on public.message_reads for all to authenticated using (user_id=auth.uid() and exists(select 1 from public.conversation_members cm join public.messages m on m.conversation_id=cm.conversation_id where m.id=message_id and cm.user_id=auth.uid())) with check (user_id=auth.uid() and exists(select 1 from public.conversation_members cm join public.messages m on m.conversation_id=cm.conversation_id where m.id=message_id and cm.user_id=auth.uid()));
