-- LarpTok v0.3 Discovery
create table if not exists public.hashtags (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.post_hashtags (
  post_id bigint not null references public.posts(id) on delete cascade,
  hashtag_id bigint not null references public.hashtags(id) on delete cascade,
  primary key (post_id, hashtag_id)
);

create table if not exists public.search_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  query text not null,
  created_at timestamptz not null default now()
);

create index if not exists hashtags_name_idx on public.hashtags(name);
create index if not exists post_hashtags_hashtag_idx on public.post_hashtags(hashtag_id);
create index if not exists post_hashtags_post_idx on public.post_hashtags(post_id);
create index if not exists search_history_user_created_idx on public.search_history(user_id, created_at desc);
create index if not exists posts_created_at_idx on public.posts(created_at desc);
create index if not exists profiles_username_idx on public.profiles(username);

create or replace function public.extract_post_hashtags()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  tag text;
  hid bigint;
begin
  delete from public.post_hashtags where post_id = new.id;
  if new.caption is null then return new; end if;
  for tag in select distinct lower((m)[1]) from regexp_matches(new.caption, '#([a-zA-Z0-9_]{1,50})', 'g') as m loop
    insert into public.hashtags(name) values (tag)
    on conflict (name) do update set name = excluded.name
    returning id into hid;
    insert into public.post_hashtags(post_id, hashtag_id) values (new.id, hid)
    on conflict do nothing;
  end loop;
  return new;
end;
$$;

drop trigger if exists posts_extract_hashtags on public.posts;
create trigger posts_extract_hashtags
after insert or update of caption on public.posts
for each row execute function public.extract_post_hashtags();

insert into public.hashtags(name)
select distinct lower((m)[1])
from public.posts p
cross join lateral regexp_matches(coalesce(p.caption,''), '#([a-zA-Z0-9_]{1,50})', 'g') as m
on conflict (name) do nothing;

insert into public.post_hashtags(post_id, hashtag_id)
select distinct p.id, h.id
from public.posts p
cross join lateral regexp_matches(coalesce(p.caption,''), '#([a-zA-Z0-9_]{1,50})', 'g') as m
join public.hashtags h on h.name = lower(m[1])
on conflict do nothing;

alter table public.hashtags enable row level security;
alter table public.post_hashtags enable row level security;
alter table public.search_history enable row level security;

drop policy if exists "Anyone can view hashtags" on public.hashtags;
create policy "Anyone can view hashtags" on public.hashtags for select using (true);

drop policy if exists "Anyone can view post hashtags" on public.post_hashtags;
create policy "Anyone can view post hashtags" on public.post_hashtags for select using (true);

drop policy if exists "Users manage own search history" on public.search_history;
create policy "Users manage own search history" on public.search_history
for all to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());