-- LarpTok v0.8 Stories
create table if not exists public.stories (
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 text text check (text is null or char_length(text)<=500),
 media_url text,
 media_type text,
 privacy text not null default 'everyone' check (privacy in ('everyone','followers','friends')),
 created_at timestamptz not null default now(),
 expires_at timestamptz not null default (now()+interval '24 hours'),
 check (text is not null or media_url is not null)
);
create table if not exists public.story_views (story_id bigint not null references public.stories(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,viewed_at timestamptz not null default now(),primary key(story_id,user_id));
create table if not exists public.story_reactions (story_id bigint not null references public.stories(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,reaction text not null default '❤️',created_at timestamptz not null default now(),primary key(story_id,user_id));
create table if not exists public.story_replies (id bigint generated by default as identity primary key,story_id bigint not null references public.stories(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,body text not null check(char_length(body) between 1 and 1000),created_at timestamptz not null default now());
create index if not exists stories_active_idx on public.stories(expires_at,created_at desc);
create index if not exists stories_user_idx on public.stories(user_id,created_at desc);
create index if not exists story_views_story_idx on public.story_views(story_id,viewed_at desc);
create index if not exists story_replies_story_idx on public.story_replies(story_id,created_at desc);
alter table public.stories enable row level security;alter table public.story_views enable row level security;alter table public.story_reactions enable row level security;alter table public.story_replies enable row level security;
create or replace function public.can_view_story(p_story_id bigint,p_user_id uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.stories s where s.id=p_story_id and s.expires_at>now() and (s.privacy='everyone' or s.user_id=p_user_id or (s.privacy='followers' and exists(select 1 from public.follows f where f.follower_id=p_user_id and f.following_id=s.user_id)))); $$;
create policy "active stories are viewable" on public.stories for select to authenticated using (expires_at>now() and (privacy='everyone' or user_id=auth.uid() or public.can_view_story(id)));
create policy "users create own stories" on public.stories for insert to authenticated with check(user_id=auth.uid());create policy "users update own stories" on public.stories for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());create policy "users delete own stories" on public.stories for delete to authenticated using(user_id=auth.uid());
create policy "viewers record story views" on public.story_views for insert to authenticated with check(user_id=auth.uid() and public.can_view_story(story_id));create policy "story owners and viewers can read views" on public.story_views for select to authenticated using(user_id=auth.uid() or exists(select 1 from public.stories s where s.id=story_id and s.user_id=auth.uid()));
create policy "viewable story reactions" on public.story_reactions for select to authenticated using(public.can_view_story(story_id));create policy "users react to viewable stories" on public.story_reactions for insert to authenticated with check(user_id=auth.uid() and public.can_view_story(story_id));create policy "users manage own reactions" on public.story_reactions for delete to authenticated using(user_id=auth.uid());
create policy "viewable story replies" on public.story_replies for select to authenticated using(public.can_view_story(story_id));create policy "users reply to viewable stories" on public.story_replies for insert to authenticated with check(user_id=auth.uid() and public.can_view_story(story_id));create policy "users delete own story replies" on public.story_replies for delete to authenticated using(user_id=auth.uid());
